name: MasksOfEternity
version: ${version}
main: dev.thelecrafter.plugins.masksofeternity.MasksOfEternityPlugin
api-version: 1.17
authors: [ TheLeCrafter ]
description: Collect powerful masks and search for deep dungeons
depend:
  - WorldEdit
commands:
  eternalitem:
    permission: masksofeternity.command.eternalitem
  opendoor:
    usage: /opendoor
  closedoor:
    usage: /closedoor
