# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
        architecture: x64
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
    - name: Cache Gradle packages
      uses: actions/cache@v2.1.6
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle
        restore-keys: ${{ runner.os }}-gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew shadowJar
    - name: Create worflow pre release
      uses: ncipollo/release-action@v1.8.6
      with:
        artifacts: "build/libs/*.jar"
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        artifactErrorsFailBuild: false
        draft: true
        prerelease: true
        release_name: "Workflow Auto Pre Release"
        tag_name: ${{ github.ref }}
        
        
